export { createArtist } from "./individual/createArtist.service";
export { getArtistById } from "./individual/getArtistById.service";
export { updateArtistMain } from "./individual/updateArtistMain.service";
export { updateBusinessAddress } from "./individual/updateBusinessAddress.service";
export { updateWarehouseAddress } from "./individual/updateWarehouseAddress.service";
export { updateDocuments } from "./individual/updateDocuments.service";
export { updateSocialLinks } from "./individual/updateSocialLinks.service";
export { deleteArtist } from "./individual/deleteArtist.service";
export { listArtists } from "./individual/listArtists.service";
